apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hemlapi-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
      - stage.anbumani.dev
      secretName: kubehelm-cert
  rules:
   - host: stage.anbumani.dev
     http:
      paths: 
      - path: /?(.*)
        backend:
          serviceName: {{ .Release.Name }}-kubehelmapi-service
          servicePort: {{ .Values.kubehelmapi.service.port }}