apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: certsync
  namespace: default
spec:
  vault:
    name: KubeHelmSSL
    object:
      name: kubehelmsslcert
      type: certificate
  output:
    secret:
      name: kubehelm-cert
      type: kubernetes.io/tls